global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'machlegiaduy2005@gmail.com'
  smtp_auth_username: 'machlegiaduy2005@gmail.com'
  smtp_auth_password: '${SMTP_AUTH_PASSWORD}'
  smtp_require_tls: true

route:
  receiver: 'email-alert'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1m

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'machlegiaduy2005@gmail.com'
        send_resolved: true