defaultRules:
  create: true
  rules:
    kubeControllerManager: false
    kubeScheduler: false
    general: false
    kubePrometheusGeneral: false

alertmanager:
  enabled: true

  alertmanagerSpec:
    replicas: 1
    configSecret: alertmanager-config

prometheus:
  prometheusSpec:
    retention: 7d

grafana:
  adminPassword: admin