apiVersion: batch/v1
kind: Job
metadata:
  generateName: seed-job-
spec:
  template:
    spec:
      containers:
      - name: seed
        image: BACKEND_IMAGE
        imagePullPolicy: Always
        command: ["node", "src/seed.js"]
        env:
        - name: MONGO_URI
          value: mongodb://mongo-service:27017/gamedb
      restartPolicy: Never
  backoffLimit: 2