services:
  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo-service
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: