apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: memory-alert
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: memory.rules
      rules:
        - alert: HighMemoryUsage
          expr: sum(container_memory_usage_bytes{namespace="production", container!=""}) by (pod) > 200000000
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Beyond Memory Usage Threshold"
            description: "Memory usage > 500MB"