apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-down-alert
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: pod.rules
      rules:
        - alert: PodDown
          expr: kube_pod_status_ready{condition="true", namespace="production"} == 0
          for: 30s
          labels:
            severity: critical
          annotations:
            summary: "Pod is down"
            description: "Pod is not ready"